### PR TITLE
Fix Winodws tests https://github.com/terkelg/tiny-glob/issues/15

### PR DESCRIPTION
**Pull request by mubaidr**

### CODE REVIEW

**Comment by terkelg** [comment]
Thanks @mubaidr! Now that I've seen your PR I actually think this is something that should be fixed in the `globrex` module.

**Comment by terkelg** [comment]
@mubaidr can you please have a look at the win branch? I tried to update `globrex` to have support for window paths?

**Comment by lukeed** [comment]
I think this'll be easier to track & crack with AppVeyor setup on `globrex` too

**Comment by mubaidr** [comment]
@terkelg Sure, will do.

**Pull request closed without merging**
