### PR TITLE
add typescript support

### PR DESCRIPTION
**Pull request by kuitos**
This change is [Reviewable](https://reviewable.io/reviews/terkelg/tiny-glob/20)

### CODE REVIEW

**Comment by kuitos** [comment]
@terkelg Are u free to review it?

**Comment by terkelg** [comment]
Hi - thanks for the PR. I'm currently working on the next version with windows support and minor changes to the option. I hope to release it within the next 2-3 days. Cool if we wait to after that?

**Comment by kuitos** [comment]
awesome,  expecting the next version!

**Comment by terkelg** [comment]
You can follow along in the `next` branch

**Comment by terkelg** [comment]
Windows support is now added. Feel free to update your PR #22

**Comment by kuitos** [comment]
I have checked the related commits, they did not affect the typings.
And which branch should this pr based now, master or next?

**Comment by lukeed** [comment]
You can rebase from `master` -- the `next` branch was just merged into it :)

**Comment by kuitos** [comment]
@terkelg sorry, anything happened?

**Comment by terkelg** [comment]
Hey @kuitos I closed because you didn't update the PR to fix the merge issues after https://github.com/terkelg/tiny-glob/pull/20#issuecomment-388671010 and therefore assumed it was inactive. I can open the issue if you still wanna help with typescript support

**Comment by kuitos** [comment]
@terkelg will it be published these days?

**Comment by terkelg** [comment]
Just published it 👍

**Pull request merged**
