### PR TITLE
Regenerate package-lock with dev flags

### PR DESCRIPTION
**Pull request by benmccann**
https://github.com/terkelg/tiny-glob/commit/1ea4098b65583adfc591c91be34789c666fb8576 should have updated the `package-lock.json` as well. When you run `npm install` it will set `"dev": true` on the dev dependencies in `package-lock.json`

### CODE REVIEW

**Comment by terkelg** [comment]
This is going to be released as `v0.2.8`

**Comment by benmccann** [comment]
I don't think it needs a new release. Shouldn't have any impact on users

**Comment by terkelg** [comment]
Oh well, I already pushed a new version before I saw your comment

**Comment by benmccann** [comment]
doesn't hurt :smile:

**Pull request merged**
